[service]
host = "127.0.0.1"
port = 5000

[database]
url = "db/test.db"

[email]
key = "secret"
base_url = "https://api.sendinblue.com/v3/"
template_id = 89
send_limit = 4

[jwt]
key = "secret"

[secrets]
vault = "secure/test.json"
key = "secure/test.key"

[wallet]
chain_id = 1337
private = "08266d3c24aaa41651c4b9bd7ca52c937afe6a535a0f735dd3c7168fe01741ee"
rpc = "http://localhost:8545"
