[service]
host = "127.0.0.1"
port = 5000

[database]
url = "db/test.db"

[email]
# key = "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"
key = "secret"
base_url = "https://api.sendinblue.com/v3/"
template_id = 2
send_limit = 4

[jwt]
key = "secret"

[secrets]
vault = "secure/test.json"
key = "secure/test.key"

[wallet]
chain_id = 80001
private = "08266d3c24aaa41651c4b9bd7ca52c937afe6a535a0f735dd3c7168fe01741ee"
rpc = "https://polygon-mumbai.g.alchemy.com/v2/WY_VYkPKizVcctkBg5Cp4BP4EI9_K3lZ"
